spring:
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: none
        show-sql: true
            
    cloud:
        bus:
            enabled: true