spring:
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: create
        show-sql: true
            
    data:
        redis:
            host: redis-service
            port: 6379
            password: 
            timeout: 6000s
            
    cloud:
        bus:
            enabled: true