server:
  port: 8080

spring:
  application:
    name: gateway-service
  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      # cors 설정
      # 모든 요청이 gateway를 통해 들어오므로, CORS 설정을 gateway에서 처리
      globalcors:
        corsConfigurations:
            '[/**]': # 모든 경로에 대해 CORS 설정 적용 -> 아래와 합하면 localhost:3000에서 오는 요청에 대해 CORS 허용
              allowedOrigins: "lb://localhost:3000" # React 앱이 실행되는 주소
              allowedMethods: "GET,POST,PUT,DELETE,OPTIONS" # 허용할 lb 메서드
              allowedHeaders: "*" # 모든 헤더 허용
              exposedHeaders: "*" # 모든 헤더 노출
              allowCredentials: true # 쿠키 허용


      routes:
        - id: user-service 

          predicates:
            - Path=/user-service/**
          uri: lb://user-service 
          filters:
          - StripPrefix=1 

        - id: payment-service
          predicates:
            - Path=/payment-service/**
          uri: lb://payment-service
          filters:
          - StripPrefix=1
jwt:
  secret: ${JWT_SECRET:daniel0h-this-is-my-secret-key-123456789}

