server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: lb://user-service
          filters:
            - StripPrefix=1
        
        - id: my-bill-service
          predicates:
            - Path=/my-bill-service/**
          uri: lb://my-bill-service
          filters:
            - StripPrefix=1

        - id: payment-service
          predicates:
            - Path=/payment-service/**
          uri: lb://payment-service
          filters:
            - StripPrefix=1

        - id: template-service
          predicates:
            - Path=/template-service/**
          uri: lb://template-service
          filters:
          - StripPrefix=1

        - id: notification-service
          predicates:
            - Path=/notification-service/**
          uri: lb://notification-service
          filters:
          - StripPrefix=1
          
        - id: external-billing-service
          predicates:
            - Path=/external-billing-service/**
          uri: lb://external-billing-service
          filters:
            - StripPrefix=1

jwt:
  secret: ogolgye-super-secret-key-for-jwt-forwebstudy