spring:
  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      # cors 설정
      # 모든 요청이 gateway를 통해 들어오므로, CORS 설정을 gateway에서 처리
      globalcors:
        corsConfigurations:
            '[/**]': # 모든 경로에 대해 CORS 설정 적용 -> 아래와 합하면 localhost:3000에서 오는 요청에 대해 CORS 허용
              allowedOrigins: "http://localhost:3000" # React 앱이 실행되는 주소
              allowedMethods: "GET,POST,PUT,DELETE,OPTIONS, PATCH" # 허용할 http 메서드
              allowedHeaders: "*" # 모든 헤더 허용
              exposedHeaders: "*" # 모든 헤더 노출
              allowCredentials: true # 쿠키 허용

      # eureka server에 등록된 client를 찾아서 사용자의 url_pattern을 매칭하는 작업
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: http://user-service
          filters:
            - StripPrefix=1
        
        - id: my-bill-service
          predicates:
            - Path=/my-bill-service/**
          uri: http://my-bill-service
          filters:
            - StripPrefix=1

        - id: payment-service
          predicates:
            - Path=/payment-service/**
          uri: http://payment-service
          filters:
            - StripPrefix=1
            
        - id: external-billing-service
          predicates:
            - Path=/external-billing-service/**
          uri: http://external-billing-service
          filters:
            - StripPrefix=1

jwt:
  secret: ogolgye-super-secret-key-for-jwt-forwebstudy
