# 공통 설정
spring:
  kafka:
    bootstrap-servers: kafka-service:9092
  # JPA 공통 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

feign:
  circuitbreaker:
    enabled: true
  bill-service:
    url: localhost:8083 

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failureRateThreshold: 40
        waitDurationInOpenState: 10000

---
# local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/don-forget}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

---
# server
spring:
  config:
    activate:
      on-profile: server
server:
  port: 8080 
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}