spring:
  kafka:

    bootstrap-servers: kafka-service:9092

feign:
  circuitbreaker:
    enabled: true


resilience4j:
  circuitbreaker:
    instances:
      externalBillingService:
        failureRateThreshold: 40
        waitDurationInOpenState: 10000 
      productService:
        failureRateThreshold: 40
        waitDurationInOpenState: 10000